#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 465
#    username: preasim.kr@gmail.com
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true
